// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg1g_wAE93wVcqK1ozvCu1DcFF-Vw0YlE',
    appId: '1:955693178050:web:8dbd7bf2139e56cf6e6f5b',
    messagingSenderId: '955693178050',
    projectId: 'udamely-9f952',
    authDomain: 'udamely-9f952.firebaseapp.com',
    storageBucket: 'udamely-9f952.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrAodZh7PmRz0yIwG1T5CTiL-Ghog076I',
    appId: '1:955693178050:android:706c165221e36b846e6f5b',
    messagingSenderId: '955693178050',
    projectId: 'udamely-9f952',
    storageBucket: 'udamely-9f952.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLFkqsJv41PA3FtcXL-ukTwy4Jks1Txmo',
    appId: '1:955693178050:ios:849060d20d17b1666e6f5b',
    messagingSenderId: '955693178050',
    projectId: 'udamely-9f952',
    storageBucket: 'udamely-9f952.appspot.com',
    iosClientId: '955693178050-f3vmbgkej1i8fhkfsfbcuerc6257dhuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLeaning2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLFkqsJv41PA3FtcXL-ukTwy4Jks1Txmo',
    appId: '1:955693178050:ios:849060d20d17b1666e6f5b',
    messagingSenderId: '955693178050',
    projectId: 'udamely-9f952',
    storageBucket: 'udamely-9f952.appspot.com',
    iosClientId: '955693178050-f3vmbgkej1i8fhkfsfbcuerc6257dhuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLeaning2',
  );
}
